---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-data
  namespace: monitoring
  labels:
    type: local
    app: prometheus-deployment
spec:
  storageClassName: "local"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /prometheus-persistant-volume
